### ISSUE TITLE
Sample/tutorial on "Category"

### ISSUE THREAD

**Issue by GMZ21931** [TextRazor/textrazor-python#11]
Hi,

Great work on TextRazor!

Is it possible to give an example on the "Category" (textrazor.ScoredCategory Object)?

I read through the documentation on https://www.textrazor.com/docs/python#Topic and had several attemps, but still don't get it right.

This is what I tried:

`import textrazor`
`textrazor.api_key = "API_KEY_HERE"`

`manager = textrazor.ClassifierManager()`
`test_classifier_id = "my_test_classifier"`

`client = textrazor.TextRazor(extractors=["topics"])`
`response = client.analyze('Although it is very early in the process, higher-level parallelism is slated to be a key theme of the next version of C++, says Bjarne Stroustrup')
`
`for entity in response.categories():`
    `print (entity.label)`

Thank you.

**Comment by crayston** [comment]
Hi! To retrieve "Category" objects in the response you need to add them to the request before calling analyze, for example: 

`client.set_classifiers("textrazor_iab")`

"Categories" are different to "Topics" and serve a slightly different purpose. "Topics" are an ever expanding unstructured set of high level themes that TextRazor can detect in your content. Categories are similar, but can only belong to a fixed Taxonomy from a classifier, which is useful if you need to classify to a known set of categories. 

If you need any help please drop us an email at support@textrazor.com
