### ISSUE TITLE
Can't set a classifier

### ISSUE THREAD

**Issue by fabiolab** [TextRazor/textrazor-python#12]
Hey
Thanks for the great job. Textrazor is amazing and the python client is great.
Therefore, I have a problem when trying to set a classifier.

Such a code:
```
client = textrazor.TextRazor(extractors=["entities", "topics"])
client.set_classifiers("textrazor_iab")   # as given in the comment of the source code (textrazor.py, line 1527)
response = client.analyze(text)
```
raises an exception on runtime:
```
  File "~/.local/share/virtualenvs/p3.7/lib/python3.7/site-packages/textrazor.py", line 210, in do_request
    raise TextRazorAnalysisException("TextRazor returned HTTP Code %d: %s" % (e.code, e.read()))
textrazor.TextRazorAnalysisException: TextRazor returned HTTP Code 400: b'{"time":0,"error":"Classifier could not be found: t ","ok":false}'
```
Have the classifiers names changed ?
Thanks for your help !

**Comment by fabiolab** [comment]
Ok, the parameter is a list, not a string. Sorry :(

**Comment by crayston** [comment]
Hey Fabrice, thanks for your kind words! The "set_classifiers" method takes a list of classifier names, so it should be:

`client.set_classifiers(["textrazor_iab",])`

At the moment it's interpreting the string as a list of separate single character classifier names.  That comment is a little out of date too, we now support two new classifiers on https://www.textrazor.com/classification which you might like to try.

**Comment by fabiolab** [comment]
Thanks for your quick answer, and sorry again for the fake issue :(
