### ISSUE TITLE
At my wits end lol - Textrazor dictionary issue

### ISSUE THREAD

**Issue by reconrad48** [TextRazor/textrazor-python#14]
I've been working on this for a few days... I am new yes, but I hate not figuring something out. I have read documentations until my eyes hurt, and I've have made at least a few hundreds attempts to get this script working. 

Any help would be greatly appreciated. 

It's the the "import textrazor.py" file, thanks

https://github.com/reconrad48/github-1

**Comment by crayston** [comment]
Hi Ralph, it looks like your `get_row_data_for_data_type` function is being passed Python dictionaries, so you are hitting an error when you try to call item.id. You could change this to `item.get('id', ''),` like you use for the "entities" response above. Alternatively, there's no need to unpack these to dicts in `extract_all_data` and you could simply pass around the TextRazor result objects.
Finally it looks like the `return extracted_data` line 319 is indented too far, right now you will only be retrieving results matching the first batch. You would just need to remove 4 spaces to make it in line with the main function body to fix that.

**Comment by crayston** [comment]
Since there isn't an issue with the library itself I'll close this for now. If you have any further trouble feel free to get in touch again at support@textrazor.com.

**Comment by reconrad48** [comment]
do you guy have a regular discussion forum? Thanks for taking a look at it... I have some other questions, I'll email.
