### ISSUE TITLE
TextRazor API does not return topics

### ISSUE THREAD

**Issue by zero141** [TextRazor/textrazor-python#16]
client = textrazor.TextRazor(extractors=["topics"])
        client.set_classifiers(['textrazor_mediatopics'])
        string = '12 3 30 workout,30 under 30,75 hard,75 hard challenge,75 hard challenge rules,75 hard rules,academy sports,adani net worth,aed to inr,aed to lkr,aed to pkr,aew,ai image generator,ai tools,airbnb,alabama woman missing,amazon prime,amber heard,american airlines promo code,american express black card,amex black card,amex centurion,angelina jolie,apple,apple iphone 15,apple iphone 15 pro max,apple vision pro,aritzia,armie hammer,ashwagandha,ashwagandha benefits,asus rog ally,athletic greens,attack on titan season 4 part 3,aud to usd,autogpt,balenciaga meme,bank of america near me,barbie box office,barca,barcelona,barcelona fc,bernard arnault,best ai stocks,best airlines,best chase credit card,best credit cards,best credit cards 2023,best dating apps,best fuel injector cleaner,best mattress 2023,best mouthwash,best multivitamin for men,best pet insurance,best pre workout,best protein powder,best vpn,best walking shoes for women,bill clinton kid,bill gates,billionaire,billionaire list,billionaires,billionaires real time,bitcoin,bitcoin price,black,black mirror season 6,black mirror season 6 ranked,bmi calculator,bob duggan forbes,body fat percentage,btc,btc price,bts,bud light controversy,cad to usd,calorie calculator,cambio dolar canadiano euro,canelo,carlee russell,carlee russell found,carta dedicata a te,cash app,cbd gummies,celebrity deaths 2023,champions league,chase bank,chase bank near me,chat gpt,chatgpt,cheapest states to live in,chest exercises,cleopatra netflix,connections hint,conor mcgregor,cracker barrel,cristiano ronaldo,crypto,crypto trading platform australia,currency converter,daniel penny gofundme,dating sites,delta 8 vs delta 9,demon slayer,demon slayer hashira training arc,destiny 2,diablo 4,diablo 4 early access,diablo 4 lilith statue map,diablo 4 season 1,dirham to pkr,djokovic,dollar to cedi,dollar to cedis,dollar to egp,dollar to euro,dollar to naira,dollar to pkr,dollar x real,doordash promo code,dr squatch discount code,drake,elizabeth holmes,elon musk,elon musk net worth,elon musk twitter,ethereum,ethereum price,euphoria,euro to aed,euro to dollar,euro to inr,fabrizio romano,fantastic four,fast and furious,fc barcelona,firefly lane,fiverr promo code,fleabag season 3,forbes,forbes 30 under 30,forbes billionaire list,forbes billionaires,forbes billionaires list,forbes college rankings,forbes list,forbes real time,forbes real time billionaires,forbes real time billionaires list,forbes richest,forbes richest list,forbes richest people,forbes richest people in the world,from season 2,from season 2 episode 7,gaslight,gaslighting,gaslighting meaning,george soros,golo reviews,google flights,google image search,google photos,google voice,grimace shake,grimace shake meme,grimace shake meme explained,gta 6,gta 6 release date,hard 75,high yield savings account,highest paid athletes,housing market,how many calories should i eat,how often do you think about the roman empire,how to get rid of gnats,how to lose weight fast,how to make money online,how to start a business,huggy wuggy,hulu,i am a surgeon,ikea discount code,invincible season 2,ios 16.4.1,ios 16.5,ios security response 16.4 1 a,iphone,iphone 15,iphone 15 colors,iphone 15 leaks,iphone 15 price,iphone 15 pro,iphone 15 pro max,iphone 15 pro max price,iphone 15 pro max release date,iphone 15 release date,irs,jedi survivor update,jeff bezos,jennifer lawrence,jessica alba,jimin,johnny depp,kanye west,kanye west net worth,kazumi,kim kardashian,kylian mbappé,kylie jenner,la liga,layoffs,lebron james,lebron james net worth,leonardo dicaprio,liam hemsworth,liam hemsworth witcher,lionel messi,liquid iv,lista forbes billionaires,love languages,lululemon,madonna,magnesium glycinate,mark cuban,mark zuckerberg,mark zuckerberg vs elon musk,mbappe,mbti test,meal replacement shakes,messi,metro boomin,michael jordan,michael rubin,modular sofa,money in the bank 2023 results,mortgage calculator,mortgage rates,most dangerous cities in america,most dangerous cities in the us,most dangerous cities in us,most secure crypto exchange australia,most valuable sports teams,mukesh ambani,naira to dollar,nasdaq: aapl,navy federal,netflix costo,neurodivergent,new iphone 2023,newegg promo code,neymar,nima momeni,noom reviews,normal heart rate by age,north sentinel island,novak djokovic,ozempic,ozempic for weight loss,ozempic weight loss,past lives,paul tassi forbes,paycheck calculator,pet insurance,pickleball,pixel 8,pizza hut,plenty of fish,pof,pound to euro,ps plus games june 2023,ps5,psg,queen cleopatra,queen cleopatra netflix,quordle,quordle answer today,quordle hint,quordle hints,quordle today,rapid security response 16.4 1,raw results,real madrid,real time billionaires,real time forbes,real time net worth,recession,redfall,resting heart rate by age,rfk jr,richest athletes in the world,richest man in the world,richest man in world,richest men in the world,richest people in the world,richest person in the world,richest person in world,rihanna,riyal to pak,riyal to pkr,ronaldo,rupert murdoch,safest australian crypto exchange,safest cities in america,safest cities in the us,safest crypto exchange australia,sam bankman-fried,sar to inr,sar to php,sar to pkr,saudi arabia riyal to pakistani rupees today,saudi currency rate in pakistan,scarlett johansson,seatgeek promo code,side hustles,silo season 2,skims discount code,sound of freedom,sound of freedom controversy,starfield,stockx discount code,student loan debt relief supreme court,student loan forgiveness,student loan forgiveness update,student loans,summerslam 2023 results,superman and lois,supreme court student loan debt relief,sweet magnolias,tax brackets 2023,taylor swift,tdee calculator,the bear,the doors of stone,the flash,the lincoln lawyer,the walking dead,the witcher,the witcher season 3,tiktok,today"s wordle,today"s wordle answer,top 10 richest man in the world,top 10 richest person in the world,top 10 richest person in world,top richest person in the world,travel insurance,trump,trump mugshot,tucker carlson,tucker carlson twitter,twisted metal,uber eats promo code,uhaul discount code,ukraine,uniqlo,uscis,usd to aed,usd to cad,usd to egp,usd to eur,usd to inr,usd to lkr,usd to pkr,usd to pkr open market,vending machine business,victor wembanyama stats,vince mcmahon,vivek ramaswamy,vivek ramaswamy net worth,vpn,warren buffett,what is 75 hard,what is the grimace shake,when do student loans resume,will mortgage rates go down,witcher,witcher season 3,wordle,wordle answer,wordle answer today,wordle hint,wordle hint today,wordle hints,wordle today,world richest man,world richest person,world top 10 richest person,world"s richest man,world"s richest person,worlds richest,wwe,wwe raw results,xo kitty,xrp,xrp news,xvideos,yasiel puig,yellowjackets season 2,2022 tax brackets,2023 tax brackets,30 under 30,401k contribution limits 2023,75 hard,75 hard challenge,75 hard rules,adrenochrome,aew,ag1 promo code,ai,ai generated images,ai image generator,ai music generator,ai photo generator,ai stocks,ai tools,alex konrad forbes,alexandr wang,altar of lilith map,altars of lilith map,american airlines promo code,american express black card,amex black card,amex centurion,apple,apple iphone 15,apple iphone 15 pro max,apple vision pro,apple vr,apple watch ultra 2,ashwagandha,ashwagandha benefits,attack on titan season 4 part 3,auto gpt,autogpt,backcountry promo code,baldur"s gate 3,balenciaga,balenciaga meme,barbie,barbie box office,barbie reviews,barca,barcelona,bernard arnault,best ai stocks,best ai tools,best airline credit card,best airlines,best antivirus,best antivirus 2023,best business credit cards,best car insurance,best cash back credit cards,best cd rates,best chase credit card,best coding bootcamps,best credit card,best credit card for travel,best credit cards,best credit cards 2023,best credit cards canada,best crypto wallet,best dividend stocks,best dividend stocks 2023,best domain registrar,best electric toothbrush,best email marketing platforms,best free antivirus,best free antivirus 2023,best free password manager,best free vpn,best free website builder,best greens powder,best high yield savings account,best mattress,best mattress 2023,best meal delivery service,best money market funds,best mouthwash,best password manager,best personal loans,best pet insurance,best pickleball paddles,best pre workout,best project management software,best protein powder,best travel credit card,best travel credit cards,best travel insurance,best vpn,best vpn 2023,best vpns,best walking shoes for men,best website builder,best whey protein,biden student loan forgiveness,billionaire,billionaire list,billionaires,billionaires real time,bing ai,bitcoin,bitcoin etf,bitcoin price,black,black mirror season 6,black mirror season 6 episodes ranked,black screen,blackpink,bluesky,bob duggan forbes,body fat percentage,box office,bray wyatt,bruce rogers forbes,btc,btc price,bts,bud light,business plan template,cannabis,carlee russell,cbd gummies,cd rates,chatgpt,cheapest states to live in,cheapest vpn,china,cit bank reviews,cleopatra netflix,cloud 100,coding bootcamp,connections hint,converse promo code,costco promo code,counter strike 2,covid,creator league,crypto,crypto news,cs2,csgo 2,cyberpunk 2077,cybersecurity,david grusch,dell coupon code,destiny 2,diablo 4,diablo 4 beta,diablo 4 early access,diablo 4 lilith statue map,diablo 4 patch notes,diablo 4 season 1,dividend calculator,dropshipping,ecommerce,ein lookup,elizabeth holmes,elon musk,elon musk net worth,ethereum,ethereum price,fc barcelona,federal tax brackets,federal tax brackets 2023,fednow,financial advisor,fintech,fiverr promo code,forbes,forbes 30 under 30,forbes 30 under 30 2023,forbes 400,forbes advisor,forbes ai 50,forbes billionaire list,forbes billionaires,forbes billionaires list,forbes business council,forbes careers,forbes cloud 100,forbes cloud 100 2023,forbes college rankings,forbes council,forbes council login,forbes coupons,forbes fintech 50,forbes health,forbes list,forbes login,forbes magazine,forbes real time,forbes real time billionaires,forbes richest,forbes richest list,forbes richest people,forbes tech council,forbes tech council login,forbes technology council,forbes under 30,forbes vetted,forbes women,forfun02 pro,foul invoker of varshan,free domain,free domain name,free website builder,future of work,garmin discount code,generative ai,godaddy promo code,golo reviews,google pixel 8,grimace shake,gta 6,gta 6 release date,gymshark discount code,harrison floyd,heloc rates,high yield savings account,highest paid athletes,how to get cs2,how to lose weight fast,how to make money online,i am a surgeon,ikea discount code,ikigai,income tax calculator,instacart ipo,intel 14th gen,invincible season 2,ios security response 16.4 1 a,iphone,iphone 15,iphone 15 colors,iphone 15 launch date,iphone 15 leaks,iphone 15 price,iphone 15 pro,iphone 15 pro max,iphone 15 release date,iphone release date,iphone15,jamie foxx,jedi survivor,jeff bezos,jena mcgregor forbes,jimin,joe mckendrick forbes,jonah hill,kai cenat,kanye west,kazumi,kenrick cai,labor day sales,layoffs,life insurance,lilith altar map,linus tech tips,lionel messi,list of billionaires,macbook,macbook air,macbook pro,madden 24,mark zuckerberg,mbappe,memorial day sales,messi,meta stock,midas list,money market funds,mortgage rates,most dangerous cities in america,most dangerous cities in the us,netflix password sharing,new iphone,new iphone release date,newegg promo code,news,neymar,nickmercs,nima momeni,oppenheimer box office,oppenheimer reviews,overwatch 2 patch notes,overwatch patch notes,ozempic,paul tassi,paul tassi forbes,pet insurance,pixel 8,pixel 8 pro,prime day 2023,project management software,queen cleopatra,real madrid,real time billionaires,recession,reddit,reddit api changes,reddit blackout,redfall,redfall review,rei coupon,resting heart rate by age,retail news,richest man in the world,richest people in the world,richest person in the world,russia,sam bankman-fried,seatgeek promo code,secret invasion,shopify alternatives,side hustles,skims discount code,small business,sound of freedom,sound of freedom box office,squarespace vs wix,starfield,starfield early access,starfield early access release time,starfield release date,starfield release time,starfield review,starfield review embargo,starfield reviews,steven crowder,stockx discount code,stripe vs paypal,student loan,student loan forgiveness,student loan forgiveness 2023,student loan forgiveness update,student loans,submarine,summerslam 2023 results,supply chain,supreme court student loan forgiveness,tarkov wipe,tax brackets 2022,tax brackets 2023,taylor swift,tears of the kingdom,tesla stock,the doors of stone,the flash,the good doctor,the little mermaid,the witcher,the witcher season 3,threads,tiktok,titanic submarine,today"s wordle,todays wordle,travel insurance,trump,trump mugshot,tucker carlson,twitch,uhaul discount code,ukraine,ukraine news,unity,ups strike,venture capital,vivek ramaswamy,vivek ramaswamy net worth,vpn,warren buffett,web3,website builder,witcher season 3,wix promo code,wix vs squarespace,wix vs wordpress,woocommerce vs shopify,wordle,wordle hint,wordle hints,wordle today,wordpress vs wix,world richest man,world top 10 richest person,world"s richest man,worldcoin,worlds richest,writers strike,wwe,xqc,xrp,xrp news,youngest billionaire,zappos promo code,“cybersecurity”'
        response = client.analyze(string)
        print(response.json)
        
        
        {'response': {'language': 'eng', 'languageIsReliable': True}, 'time': 0.7188, 'ok': True}

**Comment by crayston** [comment]
Hi @zero141 , thank you for reporting this. This very long, noisy sentence looks to be confusing the topic tagger and the API isn't returning anything. We're rolling out a serverside patch in a release this week. 
More generally, Topics look for a consistent theme in your document, so the results will suffer with noisy text like this. You might find the "entities" extractor more useful, which will return a long list of everything mentioned in the document.

**Comment by zero141** [comment]
Thanks, I will wait for a fix on the server

**Comment by crayston** [comment]
The fix for this has now rolled out, thanks for the report!

**Comment by zero141** [comment]
Thanks, it works
