### ISSUE TITLE
Exceptions should be more descriptive

### ISSUE THREAD

**Issue by ezeql** [TextRazor/textrazor-python#3]
I got into a TLS certificates problem using [docker alpine python](https://hub.docker.com/_/python) environment.

Since [this exception](https://github.com/TextRazor/textrazor-python/blob/master/textrazor.py#L212) 

```
except URLError:
    raise TextRazorAnalysisException("Could not connect to TextRazor")

```

doesn't provide much information, it was an extra step in order to catch the problem and fix it.

**Comment by crayston** [comment]
Thanks for the feedback @ezeql , we should add more context to that error string. As a test case do you know the actual Exception you were getting?

**Comment by ezeql** [comment]
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

**Comment by guilhermeprokisch** [comment]
I'm having the same problem. But no idea how to fix this exception

except URLError:
    raise TextRazorAnalysisException("Could not connect to TextRazor")

**Comment by ezeql** [comment]
Are you using docker? If so it might be related to missing ssl certificates. 
You can catch the url error and pass it over to the exception text.
Ref: http://stackoverflow.com/questions/1726402/in-python-how-do-i-use-urllib-to-see-if-a-website-is-404-or-200

**Comment by guilhermeprokisch** [comment]
Hi ezeql. Thanks for the help.
No. I'm not using docker. In my case I'm having this expect:

urlopen error [Errno -3] Temporary failure in name resolution

**Comment by crayston** [comment]
Hi Guilherme, it sounds like you are having connectivity issues between your server and api.textrazor.com. There might be a number of reasons for this, we'd be happy to help debug - would you mind emailing support@textrazor.com?

**Comment by crayston** [comment]
This has been improved over the years, the client currently only captures HTTP errors, passing other exceptions up to the caller.
