### ISSUE TITLE
Suggestion: document the fact that TextRazorResponse.json exists

### ISSUE THREAD

**Issue by weijiekoh** [TextRazor/textrazor-python#6]
It would be really helpful to users if the documentation could indicate that TextRazorResponse objects have a `json` property (which is actually a native Python object), so they can be serialised, stored, and recreated if necessary.

```python
response = client.analyze_url("http://www.bbc.co.uk/news/uk-politics-18640916")
json_content = response.json
new_response = textrazor.TextRazorResponse(json_content)
```

Thanks.

**Comment by crayston** [comment]
Thanks for the feedback! Good idea, this is getting added to the docs in an update later today.
