### ISSUE TITLE
Extract sentence for the keyword

### ISSUE THREAD

**Issue by Akashtyagi** [TextRazor/textrazor-python#8]
I am using Textrazor and want to figure out the sentence from which the keywords are identified, which I am not able to. 
The documentation doesn't contain much information on it and nor found anywhere on the internet.

Can you help me figure out how can I extract the sentence related to the keyword identified.

**Comment by crayston** [comment]
Hi Akash, I just replied to your email, let's work this out there.

**Comment by fiderosado** [comment]
i have the same problem.. text me
