### ISSUE TITLE
TextRazor API does not return exact words as input

### ISSUE THREAD

**Issue by Akashtyagi** [TextRazor/textrazor-python#9]
When entered text contains string like below example:

> "Bananas" cost €40 for 12 apples.

TextRazor api returns it as 

> ``Bananas'' cost $40 for 12 apples.

Due to this mismatching of text my results are getting affected.

**Comment by crayston** [comment]
Hi Akash, since we have discussed this over email I'll close this for now. Please get in touch if you have any other questions.
